random_seed: 230213
data:
  source_url: 'http://data.insideairbnb.com/spain/catalonia/barcelona/2022-12-11/data/listings.csv.gz'
  raw_data_path: 'data/raw'
  interim_data_path: 'data/interim'
  processed_data_path: 'data/processed'
  features:
    - host_id
    - host_is_superhost
    - neighbourhood
    - property_type
    - room_type
    - accommodates
    - bathrooms
    - bathrooms_text
    - bedrooms
    - beds
    - number_of_reviews
    - review_scores_rating
  target: 'price'
  test_split_ratio: 0.2
