data:
  source_url: 'http://data.insideairbnb.com/spain/catalonia/barcelona/2022-12-11/data/listings.csv.gz'
  raw_data_path: 'data/raw'
  interim_data_path: 'data/interim'
  processed_data_path: 'data/processed'
  test_split_ratio: 0.2
