random_seed: 230213

data:
  source_url: 'http://data.insideairbnb.com/spain/catalonia/barcelona/2022-12-11/data/listings.csv.gz'
  raw_data_path: 'data/raw'
  interim_data_path: 'data/interim'
  processed_data_path: 'data/processed'
  train_data_file: 'train.csv'
  test_data_file: 'test.csv'
  train_dataset_file: 'train_dataset.bin'
  test_dataset_file: 'test_dataset.bin'
  features:
    - host_is_superhost
    - neighbourhood_group_cleansed
    - property_type
    - room_type
    - accommodates
    - bathrooms_text
    - bedrooms
    - beds
    - number_of_reviews
  target: 'price'
  test_split_ratio: 0.2

model:
  path: 'models'