name: Application Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.0
   
    - name: Install dependencies
      run: make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Format
      run: make format